// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cdsandbox.Backend.Data;

#nullable disable

namespace cdsandbox.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407102319_ChangeIdToString")]
    partial class ChangeIdToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cdsandbox.Backend.Models.CodeBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_name");

                    b.Property<string>("AuthorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_type");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("ProjectFileId")
                        .HasColumnType("integer")
                        .HasColumnName("project_file_id");

                    b.HasKey("Id")
                        .HasName("pk_code_blocks");

                    b.HasIndex("ProjectFileId")
                        .HasDatabaseName("ix_code_blocks_project_file_id");

                    b.ToTable("code_blocks", (string)null);
                });

            modelBuilder.Entity("cdsandbox.Backend.Models.ExecutionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<int>("ProjectFileId")
                        .HasColumnType("integer")
                        .HasColumnName("project_file_id");

                    b.Property<string>("StreamType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stream_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_execution_logs");

                    b.ToTable("execution_logs", (string)null);
                });

            modelBuilder.Entity("cdsandbox.Backend.Models.ProjectFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_project_files");

                    b.ToTable("project_files", (string)null);
                });

            modelBuilder.Entity("cdsandbox.Backend.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Color");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<bool>("IsAI")
                        .HasColumnType("boolean")
                        .HasColumnName("IsAI");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("cdsandbox.Backend.Models.CodeBlock", b =>
                {
                    b.HasOne("cdsandbox.Backend.Models.ProjectFile", null)
                        .WithMany("Blocks")
                        .HasForeignKey("ProjectFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_code_blocks_project_files_project_file_id");
                });

            modelBuilder.Entity("cdsandbox.Backend.Models.ProjectFile", b =>
                {
                    b.Navigation("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
